### ISSUE TITLE
Ausgewähltes Bild labeln und speichern

### ISSUE THREAD

**Issue by Foggernaut** [valeriatisch/tagmaster#22]
Aufwand 5h (Sprint 2)
Aufwand 3h (Sprint 3)

Ein Testbild sollte im Frontend über ein Tool gelabelt und abgespeichert werden können. Am Ende sollten Koordinaten entstehen, die z.B als JSON format in einer Metadatei gespeichert werden können.

**Comment by TheoHtu** [comment]
echter Aufwand bisher 4h: (haben zu spät angefangen, die Aufgabe wäre in der vorgesehenen Zeit machbar gewesen)

**Comment by Berkan-C** [comment]
echter Aufwand ( Sprint 3 ) : 7h ( Mobile labeln+Responsiveness aufwändiger als geschätzt )
