### ISSUE TITLE
Neues Project erstellen (nur UI) 

### ISSUE THREAD

**Issue by Foggernaut** [valeriatisch/tagmaster#24]
Aufwand 2h

Ein neues Projekt sollte über ein Form erstellt werden können, wodurch eine neue Seite erstellt wird, die alle Informationen des Projekts beinhaltet. 

Beispiel der Verlinkung:

Projektliste:
tagmaster.com/nutzername/projects/

Informationen zu einem Projekt

tagmaster.com/nutzername/projects/projectname

**Comment by Berkan-C** [comment]
Aufwand von 2h war richtig
