### ISSUE TITLE
Projektmanagement um Übersicht aller Projekte zu bekommen (nur UI)

### ISSUE THREAD

**Issue by Foggernaut** [valeriatisch/tagmaster#26]
Aufwand 2h

Eine Seite mit 5 Testprojekten die man anklicken kann und einen dynamischen Link zur entsprechenden Infopage des Projekts haben

**Comment by TheoHtu** [comment]
echter Aufwand: 3h (kreatives hat länger gedauert: Desgin, Beispiele etc.)

**Comment by TheoHtu** [comment]
echter Aufwand 3h: Beispiele und Design hat länger gedauert
