### ISSUE TITLE
Responsiveness checken

### ISSUE THREAD

**Issue by valeriatisch** [valeriatisch/tagmaster#54]
Aufwand 3 + 3 + 2

**Comment by TheoHtu** [comment]
Theo: geplanter Aufwand:  3h
         eigentlicher Aufwand: 2h

**Comment by prez567** [comment]
geplanter Aufwand: 2h
eigentlicher Aufwand: 5h
noch nicht fertig

**Comment by Nilinzm** [comment]
geplanter Aufwand: 2h
eigentlicher Aufwand: 2h
